const std = @import("std");

const usage =
    \\
    \\converts a binfile to a C .h file with a bytestring const literal and length
    \\usage: binh <binfile> <name> <output>
    \\binfile: any input binary file
    \\name: name of the literal. The length will be named <name>_SIZE
    \\
    \\
;

pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    const cwd = std.Io.Dir.cwd();
    const io = init.io;

    const stderr_file = std.Io.File.stderr();
    var stderr_buf: [4096]u8 = undefined;
    var stderr_writer = stderr_file.writer(io, &stderr_buf);
    const stderr = &stderr_writer.interface;

    if (args.len != 4) {
        _ = try stderr.writeAll(usage);
        try stderr.flush();
        return error.Needs3ArgumentsExact;
    }
    const input_file = try cwd.openFile(io, args[1], .{});
    defer input_file.close(io);
    var input_buf: [4096]u8 = undefined;
    var input_reader = input_file.reader(io, &input_buf);
    const input = &input_reader.interface;

    var output_file = try cwd.createFile(io, args[3], .{});
    defer output_file.close(io);
    var output_buf: [1048576]u8 = undefined;
    var output_writer = output_file.writer(io, &output_buf);
    const output = &output_writer.interface;

    try output.print(template_pre, .{
        args[2],
    });

    var count: usize = 0;
    while (input.takeByte() catch null) |char| : (count += 1) {
        try output_writer.interface.print(
            "0x{x}, ",
            .{char},
        );
        if ((count % 16) == 0) {
            try output.writeAll("\n    ");
        }
    }
    try output.print(template_post, .{
        args[2],
        count,
    });
    try output.flush();
}

const template_pre =
    \\#include <stddef.h>
    \\// generated by binh.zig
    \\const unsigned char {s}[] = {{
    \\
;

const template_post =
    \\
    \\}};
    \\const size_t {s}_SIZE = {d};
    \\
;
