name: Continuous Integration

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v2.0.5

      - name: Run `build`
        run: zig build -Dci -Dtarget=x86_64-linux-musl

      - uses: actions/upload-artifact@v4
        with:
          name: picotool
          path: zig-out/bin/*
